name: 'main'

on:
  push:
    branches:
      - 'master'
    paths:
      - .github/workflows/main.yaml
      - .github/RELEASE_DRAFT/*
      - jest.config.js
      - package.json
      - src/*
      - tests/*
      - tsconfig.json
      - yarn.lock
  pull_request:
    paths:
      - .github/workflows/main.yaml
      - .github/RELEASE_DRAFT/*
      - jest.config.js
      - package.json
      - src/*
      - tests/*
      - tsconfig.json
      - yarn.lock

jobs:
  build:
    name: Install, Lint, Test and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4
      - name: Install
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build
  release:
    if: github.ref == 'refs/heads/master'
    name: release
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4
      - name: Create Release
        uses: minddocdev/mou-release-action@master
        with:
          templatePath: RELEASE_DRAFT/default.md
          token: ${{ github.token }}
