name: "main"

on:
  push:
    branches:
    - "master"
    paths:
    - ".github/workflows/main.yaml"
    - "package.json"
    - "src/**"
    - "tests/*"
    - "tsconfig.json"
    - ".eslintrc.js"
  pull_request:
    paths:
    - ".github/workflows/main.yaml"
    - "package.json"
    - "src/**"
    - "tests/*"
    - "tsconfig.json"
    - ".eslintrc.js"

jobs:
  unit_test:
    name: unit test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v1.2.0
    - name: Lint code
      run: yarn lint
    - name: Test code
      run: yarn test
